version: "3.3"

services:
  go-ecommerce-customer:
    build: ./src/services/customer
    container_name: go-ecommerce-customer
    environment:
      MONGO_CONNECT_URI : mongodb://root:root@mongodb-ecommerce:27017/?authSource=admin&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&directConnection=true&ssl=false
      SECRET_KEY : secret
      JWT_LIFE_TIME : 14
      HTTP_PORT : :9000
      GRPC_PORT : :9100
    depends_on:
      - mongodb-ecommerce

  go-ecommerce-provider:
    build: ./src/services/provider
    container_name: go-ecommerce-provider
    environment:
      HTTP_PORT : :9001
      GRPC_PORT : :9101 
      MONGO_CONNECT_URI : mongodb://root:root@mongodb-ecommerce:27017/?authSource=admin&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&directConnection=true&ssl=false
      SECRET_KEY : secret
      JWT_LIFE_TIME : 14
    depends_on:
      - mongodb-ecommerce

  go-ecommerce-product:
    build: ./src/services/product
    container_name: go-ecommerce-product
    environment:
      HTTP_PORT : :9002
      MONGO_CONNECT_URI : mongodb://root:root@mongodb-ecommerce:27017/?authSource=admin&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&directConnection=true&ssl=false
      REDIS_ADDR : redis-ecommerce:6379
      SECRET_KEY : secret
      JWT_LIFE_TIME : 14
      PROVIDER_GRPC_SERVER_ADDR : go-ecommerce-provider:9101
      CUSTOMER_GRPC_SERVER_ADDR : go-ecommerce-customer:9100
    depends_on:
      - mongodb-ecommerce
      - go-ecommerce-customer
      - go-ecommerce-provider
      - redis-ecommerce

  go-ecommerce-cart:
    build: ./src/services/cart
    container_name: go-ecommerce-cart
    environment:
      HTTP_PORT : :9003
      GRPC_PORT : :9103
      MONGO_CONNECT_URI : mongodb://root:root@mongodb-ecommerce:27017/?authSource=admin&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&directConnection=true&ssl=false
      SECRET_KEY : secret
      JWT_LIFE_TIME : 14
      CUSTOMER_GRPC_SERVER_ADDR : go-ecommerce-customer:9100
    depends_on:
      - mongodb-ecommerce
      - go-ecommerce-customer

  go-ecommerce-order:
    build: ./src/services/order
    container_name: go-ecommerce-order
    environment:
      HTTP_PORT : :9004
      MONGO_CONNECT_URI : mongodb://root:root@mongodb-ecommerce:27017/?authSource=admin&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&directConnection=true&ssl=false
      SECRET_KEY : secret
      JWT_LIFE_TIME : 14
      CUSTOMER_GRPC_SERVER_ADDR : go-ecommerce-customer:9100
      CART_GRPC_SERVER_ADDR : go-ecommerce-cart:9103
    depends_on:
      - mongodb-ecommerce
      - go-ecommerce-customer
      - go-ecommerce-cart

  nginx-ecommerce:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - go-ecommerce-customer
      - go-ecommerce-provider
      - go-ecommerce-product
      - go-ecommerce-cart
      - go-ecommerce-order

  mongodb-ecommerce:
    image: mongo
    container_name: mongodb-ecommerce
    volumes:
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  
  redis-ecommerce:
    image: redis
    container_name: redis-ecommerce
